# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: light_bumper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12light_bumper.proto\"\xcc\x01\n\x0bLightBumper\x12\x17\n\x0flight_bump_left\x18\x01 \x01(\x08\x12\x1d\n\x15light_bump_front_left\x18\x02 \x01(\x08\x12$\n\x1clight_bump_front_center_left\x18\x03 \x01(\x08\x12%\n\x1dlight_bump_front_center_right\x18\x04 \x01(\x08\x12\x1e\n\x16light_bump_front_right\x18\x05 \x01(\x08\x12\x18\n\x10light_bump_right\x18\x06 \x01(\x08\x62\x06proto3')



_LIGHTBUMPER = DESCRIPTOR.message_types_by_name['LightBumper']
LightBumper = _reflection.GeneratedProtocolMessageType('LightBumper', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTBUMPER,
  '__module__' : 'light_bumper_pb2'
  # @@protoc_insertion_point(class_scope:LightBumper)
  })
_sym_db.RegisterMessage(LightBumper)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIGHTBUMPER._serialized_start=23
  _LIGHTBUMPER._serialized_end=227
# @@protoc_insertion_point(module_scope)
