# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsensors.proto\"\x8e\x03\n\x07Sensors\x12*\n\x0clight_bumper\x18\x01 \x01(\x0b\x32\x14.Sensors.LightBumper\x12\x1f\n\x06\x62umper\x18\x02 \x01(\x0b\x32\x0f.Sensors.Bumper\x12\x1b\n\x04wall\x18\x03 \x01(\x0b\x32\r.Sensors.Wall\x1a\xcc\x01\n\x0bLightBumper\x12\x17\n\x0flight_bump_left\x18\x01 \x01(\x08\x12\x1d\n\x15light_bump_front_left\x18\x02 \x01(\x08\x12$\n\x1clight_bump_front_center_left\x18\x03 \x01(\x08\x12%\n\x1dlight_bump_front_center_right\x18\x04 \x01(\x08\x12\x1e\n\x16light_bump_front_right\x18\x05 \x01(\x08\x12\x18\n\x10light_bump_right\x18\x06 \x01(\x08\x1a/\n\x06\x42umper\x12\x11\n\tbump_left\x18\x01 \x01(\x08\x12\x12\n\nbump_right\x18\x02 \x01(\x08\x1a\x19\n\x04Wall\x12\x11\n\twall_seen\x18\x01 \x01(\x08\x62\x06proto3')



_SENSORS = DESCRIPTOR.message_types_by_name['Sensors']
_SENSORS_LIGHTBUMPER = _SENSORS.nested_types_by_name['LightBumper']
_SENSORS_BUMPER = _SENSORS.nested_types_by_name['Bumper']
_SENSORS_WALL = _SENSORS.nested_types_by_name['Wall']
Sensors = _reflection.GeneratedProtocolMessageType('Sensors', (_message.Message,), {

  'LightBumper' : _reflection.GeneratedProtocolMessageType('LightBumper', (_message.Message,), {
    'DESCRIPTOR' : _SENSORS_LIGHTBUMPER,
    '__module__' : 'sensors_pb2'
    # @@protoc_insertion_point(class_scope:Sensors.LightBumper)
    })
  ,

  'Bumper' : _reflection.GeneratedProtocolMessageType('Bumper', (_message.Message,), {
    'DESCRIPTOR' : _SENSORS_BUMPER,
    '__module__' : 'sensors_pb2'
    # @@protoc_insertion_point(class_scope:Sensors.Bumper)
    })
  ,

  'Wall' : _reflection.GeneratedProtocolMessageType('Wall', (_message.Message,), {
    'DESCRIPTOR' : _SENSORS_WALL,
    '__module__' : 'sensors_pb2'
    # @@protoc_insertion_point(class_scope:Sensors.Wall)
    })
  ,
  'DESCRIPTOR' : _SENSORS,
  '__module__' : 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:Sensors)
  })
_sym_db.RegisterMessage(Sensors)
_sym_db.RegisterMessage(Sensors.LightBumper)
_sym_db.RegisterMessage(Sensors.Bumper)
_sym_db.RegisterMessage(Sensors.Wall)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORS._serialized_start=18
  _SENSORS._serialized_end=416
  _SENSORS_LIGHTBUMPER._serialized_start=136
  _SENSORS_LIGHTBUMPER._serialized_end=340
  _SENSORS_BUMPER._serialized_start=342
  _SENSORS_BUMPER._serialized_end=389
  _SENSORS_WALL._serialized_start=391
  _SENSORS_WALL._serialized_end=416
# @@protoc_insertion_point(module_scope)
